#-------------------------------------------------------------
# Service
#-------------------------------------------------------------
###
GET http://localhost:4004/PurchaseOrderSRV

###
GET http://localhost:4004/PurchaseOrderSRV/$metadata

#-------------------------------------------------------------
# POSet
#-------------------------------------------------------------
###
GET http://localhost:4004/PurchaseOrderSRV/POSet?$top=11

###Read Purchase orders
GET http://localhost:4004/CatalogService/POs?$top=2&$expand=Items,PARTNER_GUID

###Read Single PO - Old syntax works as its not UUID type
GET http://localhost:4004/CatalogService/POs('74867AD200E41EDBA5D8B0C98DC28052')

###Create new PO
POST http://localhost:4004/CatalogService/POs
Content-Type: application/json;IEEE754Compatible=true

{
	"CURRENCY_CODE": "EUR",
	"GROSS_AMOUNT": "3913.91",
	"NET_AMOUNT": "3289",
	"TAX_AMOUNT": "624.91",
	"NODE_KEY": "74867AD200E41EDBA5D8B0C98DC28111",
	"PO_ID": "300000300",
	"LIFECYCLE_STATUS": "N",
	"OVERALL_STATUS": "P",
	"PARTNER_GUID_NODE_KEY": "74867AD200E41EDBA5D8B06885B04052"
}

###Calling action for the Entity
POST http://localhost:4004/CatalogService/POs('74867AD200E41EDBA5D8B0C98DC2C052')/CatalogService.boost
Content-Type: application/json

{}

###Read Largest Order in system
GET http://localhost:4004/CatalogService/POs('74867AD200E41EDBA5D8B0C98DC2C052')/CatalogService.largestOrder()

###Read Largest Order in system
GET http://localhost:4004/CatalogService/POs('74867AD200E41EDBA5D8B0C98DC2C052')


#V2------------------------------------------------------
###Calling Function using V2
GET http://localhost:4004/v2/CatalogService/POs_largestOrder?ID=74867AD200E41EDBA5D8B0C98DC2C052

###Custom Action
POST http://localhost:4004/v2/CatalogService/POs_boost?NODE_KEY=74867AD200E41EDBA5D8B0C98DC2C052
Content-Type: application/json

{}


