#-------------------------------------------------------------
# Service
#-------------------------------------------------------------
###
GET http://localhost:4004/PurchaseOrderSRV

###
GET http://localhost:4004/PurchaseOrderSRV/$metadata

#-------------------------------------------------------------
# POSet - Positive Test Cases
#-------------------------------------------------------------
### Read Top 20 Purchase Orders
GET http://localhost:4004/PurchaseOrderSRV/POSet?$top=20

### Read Top 2 Purchase Orders with repective Items and Business Partners
GET http://localhost:4004/PurchaseOrderSRV/POSet?$top=2&$expand=ITEMS,BUSINESS_PARTNER

### Read Single Purchase Order
GET http://localhost:4004/PurchaseOrderSRV/POSet(ID=02BD2137-0890-1EEA-A6C2-BB55C1978999,IsActiveEntity=true)

### Read Single Purchase Order with respective Items and Business Partners
GET http://localhost:4004/PurchaseOrderSRV/POSet(ID=02BD2137-0890-1EEA-A6C2-BB55C1978999,IsActiveEntity=true)?$expand=ITEMS,BUSINESS_PARTNER

### Create New PO
POST http://localhost:4004/PurchaseOrderSRV/POSet
Content-Type: application/json;IEEE754Compatible=true

{
	"CURRENCY_code": "EUR",
	"GROSS_AMOUNT": "3913.91",
	"NET_AMOUNT": "3289",
	"TAX_AMOUNT": "624.91",
	"BUSINESS_PARTNER_ID": "74867AD2-00E4-1EDB-A5D8-B06885A56052",
	"PO_NO": "300000300",
	"LIFECYCLE_STATUS": "N",
	"OVERALL_STATUS": "P"
}

#--------------------------------------------------------------- 
# To Do: Add the service and UI
# Action - Bound  
# Action - Unbound  
# Function Import - Bound  
# Function Import - Unbound  
#--------------------------------------------------------------- 

# ###Calling action for the Entity
# POST http://localhost:4004/PurchaseOrderSRV/POSet('02BD2137-0890-1EEA-A6C2-BB55C1978999')/PurchaseOrderSRV.ActionName
# Content-Type: application/json

# {}

# ###Read Largest Order in system
# GET http://localhost:4004/PurchaseOrderSRV/POSet('02BD2137-0890-1EEA-A6C2-BB55C1978999')/PurchaseOrderSRV.functionName()

